### ISSUE TITLE
Use it with Mark Aikens PCB

### ISSUE THREAD

**Issue by tmdrews** [ThorstenBr/A2USB#2]
Does it work on Mark Aikens PCB Design with the IRQ mod? I have some PCBs from that project and would like to use one of these. That design has the advantage that it doesn't have the chunky VGA connector on board.

**Comment by ThorstenBr** [comment]
The short answer is "no".
There are a few minor and one bigger issue:
1. Mark's PCB uses a slightly different pinout (interfacing the 6502 bus etc).
2. The firmware needs to be able to respond to 6502 bus read cycles.
3. The firmware needs to respond to read cycles accessing the device ROM **_and_** register area (IOSEL + DEVSEL). Mark's PCB only connects the signal for I/O register area (DEVSEL).
The firmware could be adapted for the first issue realtively easily.
For the second issue: Mark's design no longer supports read accesses, since his firmware doesn't use it. But he still has a jumper on the board to connect the necessary signal (so the PICO can control the direction of the bus transceiver).
The third issue is the bigger one: the Mark's board does not connect both bus selection signals (IOSEL+DEVSEL). A simple "AND" gate would be required to combine these signals and a modification to the PCB (to feed the combined signal instead of just DEVSEL).
So the long answer is: it would be possible with quite a bit of work and more modifications to the firmware + hardware.

**Comment by tmdrews** [comment]
Sad, but thanks for the info. So I will try with the supported boards.
